using System.Text.Json.Serialization;

namespace ContextAwareSuggestions;

/// <summary>
/// Represents the AI-generated response returned from the Azure AI service.
/// </summary>
/// <remarks>
/// This model contains the primary answer generated by the AI model along with a collection of context-aware follow-up suggestions that can be displayed in the Syncfusion AI AssistView control.
/// </remarks>
public class ContextSuggestionResponse
{
    /// <summary>
    /// Gets or sets the answer generated by the AI service.
    /// </summary>
    [JsonPropertyName("answer")]
    public string Answer { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the collection of context-aware follow-up suggestions.
    /// </summary>
    [JsonPropertyName("suggestions")]
    public List<string> Suggestions { get; set; } = new();
}
